import 'package:flutter/material.dart';
import 'pokemon_detail_page.dart';
import 'package:pokedex_app/models/pokemon.dart';

class PokedexScreen extends StatefulWidget {
  @override
  _PokedexScreenState createState() => _PokedexScreenState();
}

class _PokedexScreenState extends State<PokedexScreen> {
  String _selectedRegion = 'All';

  List<Pokemon> _pokemonList = [
    Pokemon(name: 'Bulbasaur', type: 'Grass/Poison', imagePath: 'assets/images/bulbasaur.png', region: 'Kanto',
    entry: 'It carries a seed on its back right from birth. As its body grows larger, the seed does too.',
    ability: 'Overgrow/Chlorophyll',
    weakness: 'Fire/Ice/Flying/Psychic',
    evolutions: [
    'assets/images/bulbasaur.png',
    'assets/images/ivysaur.png',
    'assets/images/venusaur.png',
    ]
    ),
    Pokemon(name: 'Ivysaur', type: 'Grass/Poison', imagePath: 'assets/images/ivysaur.png', region: 'Kanto',
    entry: 'The bulb on its back grows as it absorbs nutrients. The bulb gives off a pleasant aroma when it blooms.',
    ability: 'Overgrow/Chlorophyll',
    weakness: 'Fire/Ice/Flying/Psychic',
    evolutions: [
    'assets/images/bulbasaur.png',
    'assets/images/ivysaur.png',
    'assets/images/venusaur.png',
    ]
    ),
    Pokemon(name: 'Venusaur', type: 'Grass/Poison', imagePath: 'assets/images/venusaur.png', region: 'Kanto',
    entry: 'A bewitching aroma wafts from its flower. The fragrance becalms those engaged in a battle.',
    ability: 'Overgrow/Chlorophyll',
    weakness: 'Fire/Ice/Flying/Psychic',
    evolutions: [
    'assets/images/bulbasaur.png',
    'assets/images/ivysaur.png',
    'assets/images/venusaur.png',
    ]
    ),
    Pokemon(name: 'Charmander', type: 'Fire', imagePath: 'assets/images/charmander.png', region: 'Kanto',
    entry: 'From the time it is born, a flame burns at the tip of its tail. Its life would end if the flame were to go out.',
    ability: 'Blaze/Solar Power',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/charmander.png',
    'assets/images/charmeleon.png',
    'assets/images/charizard.png',
    ]
    ),
    Pokemon(name: 'Charmeleon', type: 'Fire', imagePath: 'assets/images/charmeleon.png', region: 'Kanto',
    entry: 'If it becomes agitated during battle, it spouts intense flames, incinerating its surroundings.',
    ability: 'Blaze/Solar Power',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/charmander.png',
    'assets/images/charmeleon.png',
    'assets/images/charizard.png',
    ]),
    Pokemon(name: 'Charizard', type: 'Fire/Flying', imagePath: 'assets/images/charizard.png', region: 'Kanto',
    entry: 'Charizard flies around the sky in search of powerful opponents. It breathes fire of such great heat that it melts anything. However, it never turns its fiery breath on any opponent weaker than itself.',
    ability: 'Blaze/Solar Power',
    weakness: 'Water/Electric/Rock',
    evolutions: [
    'assets/images/charmander.png',
    'assets/images/charmeleon.png',
    'assets/images/charizard.png',
    ]),
    Pokemon(name: 'Squirtle', type: 'Water', imagePath: 'assets/images/squirtle.png', region: 'Kanto',
    entry: 'After birth, its back swells and hardens into a shell. It sprays a potent foam from its mouth.',
    ability: 'Torrent/Rain Dish',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/squirtle.png',
    'assets/images/wartortle.png',
    'assets/images/blastoise.png',
    ]),
    Pokemon(name: 'Wartortle', type: 'Water', imagePath: 'assets/images/wartortle.png', region: 'Kanto',
    entry: 'It often hides in water to stalk unwary prey. While swimming quickly, it moves its ears to maintain balance.',
    ability: 'Torrent/Rain Dish',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/squirtle.png',
    'assets/images/wartortle.png',
    'assets/images/blastoise.png',
    ]),
    Pokemon(name: 'Blastoise', type: 'Water', imagePath: 'assets/images/blastoise.png', region: 'Kanto',
    entry: 'It deliberately increases its body weight so it can withstand the recoil of the water jets it fires.',
    ability: 'Torrent/Rain Dish',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/squirtle.png',
    'assets/images/wartortle.png',
    'assets/images/blastoise.png',
    ]),
    Pokemon(name: 'Chikorita', type: 'Grass', imagePath: 'assets/images/chikorita.png', region: 'Johto',
    entry: 'It loves to bask in the sunlight. It uses the leaf on its head to seek out warm places.',
    ability: 'Overgrow/Leaf Guard',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/chikorita.png',
    'assets/images/bayleef.png',
    'assets/images/meganium.png',
    ]),
    Pokemon(name: 'Bayleef', type: 'Grass', imagePath: 'assets/images/bayleef.png', region: 'Johto',
    entry: 'The scent that wafts from the leaves on its neck causes anyone who smells it to become energetic.',
    ability: 'Overgrow/Leaf Guard',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/chikorita.png',
    'assets/images/bayleef.png',
    'assets/images/meganium.png',
    ]),
    Pokemon(name: 'Meganium', type: 'Grass', imagePath: 'assets/images/meganium.png', region: 'Johto',
    entry: 'Anyone who stands beside it becomes refreshed, just as if they were soaking in the soothing atmosphere of a forest.',
    ability: 'Overgrow/Leaf Guard',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/chikorita.png',
    'assets/images/bayleef.png',
    'assets/images/meganium.png',
    ]),
    Pokemon(name: 'Cyndaquil', type: 'Fire', imagePath: 'assets/images/cyndaquil.png', region: 'Johto',
    entry: 'It usually stays hunched over. If it is angry or surprised, it shoots flames out of its back.',
    ability: 'Blaze/Flash Fire',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/cyndaquil.png',
    'assets/images/quilava.png',
    'assets/images/typhlosion.png',
    ]),
    Pokemon(name: 'Quilava', type: 'Fire', imagePath: 'assets/images/quilava.png', region: 'Johto',
    entry: 'Before battle, it turns its back on its opponent to demonstrate how ferociously its fire blazes.',
    ability: 'Blaze/Flash Fire',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/cyndaquil.png',
    'assets/images/quilava.png',
    'assets/images/typhlosion.png',
    ]),
    Pokemon(name: 'Typhlosion', type: 'Fire', imagePath: 'assets/images/typhlosion.png', region: 'Johto',
    entry: 'It has a secret, devastating move. It rubs its blazing fur to cause huge explosions.',
    ability: 'Blaze/Flash Fire',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/cyndaquil.png',
    'assets/images/quilava.png',
    'assets/images/typhlosion.png',
    ]),
    Pokemon(name: 'Totodile', type: 'Water', imagePath: 'assets/images/totodile.png', region: 'Johto',
    entry: 'Its powerful, well-developed jaws are capable of crushing anything. Even its Trainer must be careful.',
    ability: 'Torrent/Sheer Force',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/totodile.png',
    'assets/images/croconaw.png',
    'assets/images/feraligatr.png',
    ]),
    Pokemon(name: 'Croconaw', type: 'Water', imagePath: 'assets/images/croconaw.png', region: 'Johto',
    entry: 'The tips of its fangs are slanted backward. Once those fangs clamp down, the prey has no hope of escape.',
    ability: 'Torrent/Sheer Force',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/totodile.png',
    'assets/images/croconaw.png',
    'assets/images/feraligatr.png',
    ]),
    Pokemon(name: 'Feraligatr', type: 'Water', imagePath: 'assets/images/feraligatr.png', region: 'Johto',
    entry: 'Although it has a massive body, its powerful hind legs enable it to move quickly, even on land.',
    ability: 'Torrent/Sheer Force',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/totodile.png',
    'assets/images/croconaw.png',
    'assets/images/feraligatr.png',
    ]),
    Pokemon(name: 'Treecko', type: 'Grass', imagePath: 'assets/images/treecko.png', region: 'Hoenn',
    entry: 'Treecko can quickly scale even vertical surfaces. It senses humidity with its tail to predict the next days weather.',
    ability: 'Overgrow/Unburden',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/treecko.png',
    'assets/images/grovyle.png',
    'assets/images/sceptile.png',
    ]),
    Pokemon(name: 'Grovyle', type: 'Grass', imagePath: 'assets/images/grovyle.png', region: 'Hoenn',
    entry: 'Its strongly developed thigh muscles give it astounding agility and jumping performance.',
    ability: 'Overgrow/Unburden',
    weakness: 'FiFire/Ice/Poison/Flying/Bugre',
    evolutions: [
    'assets/images/treecko.png',
    'assets/images/grovyle.png',
    'assets/images/sceptile.png',
    ]),
    Pokemon(name: 'Sceptile', type: 'Grass', imagePath: 'assets/images/sceptile.png', region: 'Hoenn',
    entry: 'It agilely flits through the jungle and uses the sharp-edged leaves on its arms to cut down its prey.',
    ability: 'Overgrow/Unburden',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/treecko.png',
    'assets/images/grovyle.png',
    'assets/images/sceptile.png',
    ]),
    Pokemon(name: 'Torchic', type: 'Fire', imagePath: 'assets/images/torchic.png', region: 'Hoenn',
    entry: 'Torchic feels toasty warm if you hug it. It has a flame sac inside its belly, and the flames burn continuously as long as Torchic has life in it.',
    ability: 'Blaze/Speed Boost',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/torchic.png',
    'assets/images/combusken.png',
    'assets/images/blaziken.png',
    ]),
    Pokemon(name: 'Combusken', type: 'Fire/Fighting', imagePath: 'assets/images/combusken.png', region: 'Hoenn',
    entry: 'It boosts its concentration by emitting harsh cries. Its kicks have outstanding destructive power.',
    ability: 'Blaze/Speed Boost',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/torchic.png',
    'assets/images/combusken.png',
    'assets/images/blaziken.png',
    ]),
    Pokemon(name: 'Blaziken', type: 'Fire/Fighting', imagePath: 'assets/images/blaziken.png', region: 'Hoenn',
    entry: 'When facing a tough foe, it looses flames from its wrists. Its powerful legs let it jump clear over buildings.',
    ability: 'Blaze/Speed Boost',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/torchic.png',
    'assets/images/combusken.png',
    'assets/images/blaziken.png',
    ]),
    Pokemon(name: 'Mudkip', type: 'Water', imagePath: 'assets/images/mudkip.png', region: 'Hoenn',
    entry: 'When it uses its large tail fin, it picks up speed rapidly in the water. It is strong in spite of its small size.',
    ability: 'Torrent/Damp',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/mudkip.png',
    'assets/images/marshtomp.png',
    'assets/images/swampert.png',
    ]),
    Pokemon(name: 'Marshtomp', type: 'Water/Ground', imagePath: 'assets/images/marshtomp.png', region: 'Hoenn',
    entry: 'It quickly overwhelms opponents that are bogged down and unable to move.',
    ability: 'Torrent/Damp',
    weakness: 'Grass',
    evolutions: [
    'assets/images/mudkip.png',
    'assets/images/marshtomp.png',
    'assets/images/swampert.png',
    ]),
    Pokemon(name: 'Swampert', type: 'Water/Ground', imagePath: 'assets/images/swampert.png', region: 'Hoenn',
    entry: 'Its arms are hard as rock. With one swing, it can break an enormous boulder into pieces.',
    ability: 'Torrent/Damp',
    weakness: 'Grass',
    evolutions: [
    'assets/images/mudkip.png',
    'assets/images/marshtomp.png',
    'assets/images/swampert.png',
    ]),
    Pokemon(name: 'Turtwig', type: 'Grass', imagePath: 'assets/images/turtwig.png', region: 'Sinnoh',
    entry: 'The shell on its back is made of soil. If the shell is moist to the touch, Turtwig is very healthy.',
    ability: 'Overgrow/Shell Armor',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/turtwig.png',
    'assets/images/grotle.png',
    'assets/images/torterra.png',
    ]),
    Pokemon(name: 'Grotle', type: 'Grass', imagePath: 'assets/images/grotle.png', region: 'Sinnoh',
    entry: 'It knows where pure water wells up. It carries fellow Pokémon there on its back.',
    ability: 'Overgrow/Shell Armo',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/turtwig.png',
    'assets/images/grotle.png',
    'assets/images/torterra.png',
    ]),
    Pokemon(name: 'Torterra', type: 'Grass/Ground', imagePath: 'assets/images/torterra.png', region: 'Sinnoh',
    entry: 'Ancient people imagined that beneath the ground dwelt a gigantic Torterra.',
    ability: 'Overgrow/Shell Armo',
    weakness: 'Fire/Ice/Flying/Bug',
    evolutions: [
    'assets/images/turtwig.png',
    'assets/images/grotle.png',
    'assets/images/torterra.png',
    ]),
    Pokemon(name: 'Chimchar', type: 'Fire', imagePath: 'assets/images/chimchar.png', region: 'Sinnoh',
    entry: 'It is very agile. Before going to sleep, it extinguishes the flame on its tail to prevent fires.',
    ability: 'Blaze/Iron Fist',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/chimchar.png',
    'assets/images/monferno.png',
    'assets/images/infernape.png',
    ]),
    Pokemon(name: 'Monferno', type: 'Fire', imagePath: 'assets/images/monferno.png', region: 'Sinnoh',
    entry: 'It skillfully controls the intensity of the fire on its tail to keep its foes at an ideal distance.',
    ability: 'Blaze/Iron Fist',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/chimchar.png',
    'assets/images/monferno.png',
    'assets/images/infernape.png',
    ]),
    Pokemon(name: 'Infernape', type: 'Fire/Fighting', imagePath: 'assets/images/infernape.png', region: 'Sinnoh',
    entry: 'A tall, hardy Pokémon with a dazzling appearance. It shrouds itself in flame and battles as if engaged in dance—truly a sight to behold.',
    ability: 'Blaze/Iron Fist',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/chimchar.png',
    'assets/images/monferno.png',
    'assets/images/infernape.png',
    ]),
    Pokemon(name: 'Piplup', type: 'Water', imagePath: 'assets/images/piplup.png', region: 'Sinnoh',
    entry: 'A poor walker, it often falls down. However, its strong pride makes it puff up its chest without a care.',
    ability: 'Torrent/Defiant',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/piplup.png',
    'assets/images/prinplup.png',
    'assets/images/empoleon.png',
    ]),
    Pokemon(name: 'Prinplup', type: 'Water', imagePath: 'assets/images/prinplup.png', region: 'Sinnoh',
    entry: 'Because every Prinplup considers itself to be the most important, they can never form a group.',
    ability: 'Torrent/Defiant',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/piplup.png',
    'assets/images/prinplup.png',
    'assets/images/empoleon.png',
    ]),
    Pokemon(name: 'Empoleon', type: 'Water/Steel', imagePath: 'assets/images/empoleon.png', region: 'Sinnoh',
    entry: 'Since ancient times, it has been revered by the people of Hisui, who call it the Master of the Waves. Its wings are a match for even master-crafted blades.',
    ability: 'Torrent/Defiant',
    weakness: 'Electric/Fighting/Ground',
    evolutions: [
    'assets/images/piplup.png',
    'assets/images/prinplup.png',
    'assets/images/empoleon.png',
    ]),
    Pokemon(name: 'Snivy', type: 'Grass', imagePath: 'assets/images/snivy.png', region: 'Unova',
    entry: 'The leaf on Snivys tail generates energy when exposed to sunlight, making Snivy swifter and adding an edge to its moves.',
    ability: 'Overgrow/Contrary',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/snivy.png',
    'assets/images/servine.png',
    'assets/images/serperior.png',
    ]),
    Pokemon(name: 'Servine', type: 'Grass', imagePath: 'assets/images/servine.png', region: 'Unova',
    entry: 'It runs low to the ground, weaving through the grass, then mercilessly pummels its target by whipping them with its vines.',
    ability: 'Overgrow/Contrary',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/snivy.png',
    'assets/images/servine.png',
    'assets/images/serperior.png',
    ]),
    Pokemon(name: 'Serperior', type: 'Grass', imagePath: 'assets/images/serperior.png', region: 'Unova',
    entry: 'An intimidating gaze and majestic appearance have caused this Pokémon to be known as the Lord of the Forest.',
    ability: 'Overgrow/Contrary',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/snivy.png',
    'assets/images/servine.png',
    'assets/images/serperior.png',
    ]),
    Pokemon(name: 'Tepig', type: 'Fire', imagePath: 'assets/images/tepig.png', region: 'Unova',
    entry: 'Its more nimble than it looks, and it uses its speed to confound its enemies. It rapidly launches fireballs from both nostrils.',
    ability: 'Blaze/Thick Fat',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/tepig.png',
    'assets/images/pignite.png',
    'assets/images/emboar.png',
    ]),
    Pokemon(name: 'Pignite', type: 'Fire/Fighting', imagePath: 'assets/images/pignite.png', region: 'Unova',
    entry: 'When Pignite enters battle, its body temperature rapidly soars until Pignite itself is engulfed by a scorching fireball.',
    ability: 'Blaze/Thick Fat',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/tepig.png',
    'assets/images/pignite.png',
    'assets/images/emboar.png',
    ]),
    Pokemon(name: 'Emboar', type: 'Fire/Fighting', imagePath: 'assets/images/emboar.png', region: 'Unova',
    entry: 'The flames blazing deep inside Emboars chest erupt vigorously from its chin, forming a beard of fire.',
    ability: 'Blaze/Thick Fat',
    weakness: 'Water/Ground/Flying/Psychic',
    evolutions: [
    'assets/images/tepig.png',
    'assets/images/pignite.png',
    'assets/images/emboar.png',
    ]),
    Pokemon(name: 'Oshawott', type: 'Water', imagePath: 'assets/images/oshawott.png', region: 'Unova',
    entry: 'Its said that Oshawott learned to maintain its scalchop with riverbed stones by mimicking humans it saw using whetstones.',
    ability: 'Torrent/Shell Armor',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/oshawott.png',
    'assets/images/dewott.png',
    'assets/images/samurott.png',
    ]),
    Pokemon(name: 'Dewott', type: 'Water', imagePath: 'assets/images/dewott.png', region: 'Unova',
    entry: 'Its said that people modeled swordplay after the way Dewotts movements flow like water while its wielding its two scalchops.',
    ability: 'Torrent/Shell Armor',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/oshawott.png',
    'assets/images/dewott.png',
    'assets/images/samurott.png',
    ]
    ),
    Pokemon(name: 'Samurott', type: 'Water', imagePath: 'assets/images/samurott.png', region: 'Unova',
    entry: 'A master of a sword-drawing art called iaijutsu, Samurott settles its battles with a single swing of either large sword sheathed in its foreleg armor.',
    ability: 'Torrent/Shell Armor',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/oshawott.png',
    'assets/images/dewott.png',
    'assets/images/samurott.png',
    ]),
    Pokemon(name: 'Chespin', type: 'Grass', imagePath: 'assets/images/chespin.png', region: 'Kalos',
    entry: 'Eating lots of berries makes the bark shell that covers Chespins head and body grow sturdier.',
    ability: 'Overgrow/Bulletproof',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/chespin.png',
    'assets/images/quilladin.png',
    'assets/images/chesnaught.png',
    ]),
    Pokemon(name: 'Quilladin', type: 'Grass', imagePath: 'assets/images/quilladin.png', region: 'Kalos',
    entry: 'Its protected by a sturdy shell. The shell is also very heavy, which naturally strengthens Quilladins lower body.',
    ability: 'Overgrow/Bulletproof',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/chespin.png',
    'assets/images/quilladin.png',
    'assets/images/chesnaught.png',
    ]),
    Pokemon(name: 'Chesnaught', type: 'Grass/Fighting', imagePath: 'assets/images/chesnaught.png', region: 'Kalos',
    entry: 'Its gentle disposition would have it avoid conflict, but it gives opponents a thrashing with its thorned fists when the situation calls for it.',
    ability: 'Overgrow/Bulletproof',
    weakness: 'Fire/Ice/Poison/Flying/Psychic/Fairy',
    evolutions: [
    'assets/images/chespin.png',
    'assets/images/quilladin.png',
    'assets/images/chesnaught.png',
    ]),
    Pokemon(name: 'Fennekin', type: 'Fire', imagePath: 'assets/images/fennekin.png', region: 'Kalos',
    entry: 'Twigs make for Fennekins snacks. When it nibbles on twigs, it finds the courage to face strong foes.',
    ability: 'Blaze/Magician',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/fennekin.png',
    'assets/images/braixen.png',
    'assets/images/delphox.png',
    ]),
    Pokemon(name: 'Braixen', type: 'Fire', imagePath: 'assets/images/braixen.png', region: 'Kalos',
    entry: 'It ignites the twig from its tail and waves the twig around to signal its allies. To indicate danger, it draws circles in the air with the twigs flame.',
    ability: 'Blaze/Magician',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/fennekin.png',
    'assets/images/braixen.png',
    'assets/images/delphox.png',
    ]),
    Pokemon(name: 'Delphox', type: 'Fire/Psychic', imagePath: 'assets/images/delphox.png', region: 'Kalos',
    entry: 'It leaves burn marks in the ground with the flame at the tip of its wand. Long ago, people used the shapes of these burn marks for divination.',
    ability: 'Blaze/Magician',
    weakness: 'Water/Ground/Rock/Ghost/Dark',
    evolutions: [
    'assets/images/fennekin.png',
    'assets/images/braixen.png',
    'assets/images/delphox.png',
    ]),
    Pokemon(name: 'Froakie', type: 'Water', imagePath: 'assets/images/froakie.png', region: 'Kalos',
    entry: 'It utilizes its extraordinary jumping abilities to flummox its foes, throwing springy bubbles at them from above their heads.',
    ability: 'Torrent/Protean',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/froakie.png',
    'assets/images/frogadier.png',
    'assets/images/greninja.png',
    ]),
    Pokemon(name: 'Frogadier', type: 'Water', imagePath: 'assets/images/frogadier.png', region: 'Kalos',
    entry: 'The tips of its fingers and toes stick firmly to vertical surfaces. Frogadier can scale skyscrapers with ease.',
    ability: 'Torrent/Protean',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/froakie.png',
    'assets/images/frogadier.png',
    'assets/images/greninja.png',
    ]),
    Pokemon(name: 'Greninja', type: 'Water/Dark', imagePath: 'assets/images/greninja.png', region: 'Kalos',
    entry: 'It makes shuriken out of mucus excreted from its thighs. These shuriken can cut cleanly through steel cables.',
    ability: 'Torrent/Protean',
    weakness: 'Grass/Electric/Fighting/Bug/Fairy',
    evolutions: [
    'assets/images/froakie.png',
    'assets/images/frogadier.png',
    'assets/images/greninja.png',
    ]),
    Pokemon(name: 'Rowlet', type: 'Grass/Flying', imagePath: 'assets/images/rowlet.png', region: 'Alola',
    entry: 'It feels relaxed in tight, dark places and has been known to nestle into its Trainers bag or the front of their jacket.',
    ability: 'Overgrow/Long Reach',
    weakness: 'Fire/Ice/Poison/Flying/Rock',
    evolutions: [
    'assets/images/rowlet.png',
    'assets/images/dartrix.png',
    'assets/images/decidueye.png',
    ]),
    Pokemon(name: 'Dartrix', type: 'Grass/Flying', imagePath: 'assets/images/dartrix.png', region: 'Alola',
    entry: 'It throws sharp feathers called blade quills at enemies or prey. It seldom misses.',
    ability: 'Overgrow/Long Reach',
    weakness: 'Fire/Ice/Poison/Flying/Rock',
    evolutions: [
    'assets/images/rowlet.png',
    'assets/images/dartrix.png',
    'assets/images/decidueye.png',
    ]),
    Pokemon(name: 'Decidueye', type: 'Grass/Ghost', imagePath: 'assets/images/decidueye.png', region: 'Alola',
    entry: 'It nocks its arrow quills and looses them at opponents. When it needs to hit, it pulls the vines on its hood to narrow its view and focus.',
    ability: 'Overgrow/Long Reach',
    weakness: 'Fire/Ice/Flying/Ghost/Dark',
    evolutions: [
    'assets/images/rowlet.png',
    'assets/images/dartrix.png',
    'assets/images/decidueye.png',
    ]),
    Pokemon(name: 'Litten', type: 'Fire', imagePath: 'assets/images/litten.png', region: 'Alola',
    entry: 'If you try too hard to get close to it, it wont open up to you. Even if you do grow close, giving it too much affection is still a no-no.',
    ability: 'Blaze/Intimidate',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/litten.png',
    'assets/images/torracat.png',
    'assets/images/incineroar.png',
    ]),
    Pokemon(name: 'Torracat', type: 'Fire', imagePath: 'assets/images/torracat.png', region: 'Alola',
    entry: 'At its throat, it bears a bell of fire. The bell rings brightly whenever fire spews out.',
    ability: 'Blaze/Intimidate',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/litten.png',
    'assets/images/torracat.png',
    'assets/images/incineroar.png',
    ]),
    Pokemon(name: 'Incineroar', type: 'Fire/Dark', imagePath: 'assets/images/incineroar.png', region: 'Alola',
    entry: 'When its fighting spirit is set alight, the flames around its waist become especially intense.',
    ability: 'Blaze/Intimidate',
    weakness: 'Water/Fighting/Ground/Rock',
    evolutions: [
    'assets/images/litten.png',
    'assets/images/torracat.png',
    'assets/images/incineroar.png',
    ]),
    Pokemon(name: 'Popplio', type: 'Water', imagePath: 'assets/images/popplio.png', region: 'Alola',
    entry: 'The balloons it inflates with its nose grow larger and larger as it practices day by day.',
    ability: 'Torrent/Liquid Voice',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/popplio.png',
    'assets/images/brionne.png',
    'assets/images/primarina.png',
    ]),
    Pokemon(name: 'Brionne', type: 'Water', imagePath: 'assets/images/brionne.png', region: 'Alola',
    entry: 'A skillful dancer, it creates a sequence of water balloons as it dances, then briskly bombards its enemies.',
    ability: 'Torrent/Liquid Voice',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/popplio.png',
    'assets/images/brionne.png',
    'assets/images/primarina.png',
    ]),
    Pokemon(name: 'Primarina', type: 'Water/Fairy', imagePath: 'assets/images/primarina.png', region: 'Alola',
    entry: 'Also known as a songstress, it is a sight to behold on moonlit nights when it sings in front of the colony it leads.',
    ability: 'Torrent/Liquid Voice',
    weakness: 'Grass/Electric/Poison',
    evolutions: [
    'assets/images/popplio.png',
    'assets/images/brionne.png',
    'assets/images/primarina.png',
    ]),
    Pokemon(name: 'Grookey', type: 'Grass', imagePath: 'assets/images/grookey.png', region: 'Galar',
    entry: 'As Grookey strikes everything in sight with its stick, it has more and more fun, and its rhythm becomes livelier.',
    ability: 'Overgrow/Grassy Surge',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/grookey.png',
    'assets/images/thwackey.png',
    'assets/images/rillaboom.png',
    ]),
    Pokemon(name: 'Thwackey', type: 'Grass', imagePath: 'assets/images/thwackey.png', region: 'Galar',
    entry: 'It skillfully uses its two sticks not only for drumming out rapid beats but also for pummeling opponents during battle.',
    ability: 'Overgrow/Grassy Surge',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/grookey.png',
    'assets/images/thwackey.png',
    'assets/images/rillaboom.png',
    ]),
    Pokemon(name: 'Rillaboom', type: 'Grass', imagePath: 'assets/images/rillaboom.png', region: 'Galar',
    entry: 'When one Rillaboom challenges another who leads a troop, a drumming battle commences. The victor becomes the troops new boss.',
    ability: 'Overgrow/Grassy Surge',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/grookey.png',
    'assets/images/thwackey.png',
    'assets/images/rillaboom.png',
    ]),
    Pokemon(name: 'Scorbunny', type: 'Fire', imagePath: 'assets/images/scorbunny.png', region: 'Galar',
    entry: 'Once its body has heated up, Scorbunny can use the full extent of its power. Thats why it does warm-up exercises.',
    ability: 'Blaze/Libero',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/scorbunny.png',
    'assets/images/raboot.png',
    'assets/images/cinderace.png',
    ]),
    Pokemon(name: 'Raboot', type: 'Fire', imagePath: 'assets/images/raboot.png', region: 'Galar',
    entry: 'Thanks to its soft and fluffy fur, Raboot can easily heat up its fire energy and produce flames with more power.',
    ability: 'Blaze/Libero',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/scorbunny.png',
    'assets/images/raboot.png',
    'assets/images/cinderace.png',
    ]),
    Pokemon(name: 'Cinderace', type: 'Fire', imagePath: 'assets/images/cinderace.png', region: 'Galar',
    entry: 'Using a ball that it made out of flames, Cinderace blinds its opponents and keeps them at bay.',
    ability: 'Blaze/Libero',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/scorbunny.png',
    'assets/images/raboot.png',
    'assets/images/cinderace.png',
    ]),
    Pokemon(name: 'Sobble', type: 'Water', imagePath: 'assets/images/sobble.png', region: 'Galar',
    entry: 'It gets berries to eat by shooting them down with bullets of water it spurts from its mouth. Its aim is perfect.',
    ability: 'Torrent/Sniper',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/sobble.png',
    'assets/images/drizzile.png',
    'assets/images/inteleon.png',
    ]),
    Pokemon(name: 'Drizzile', type: 'Water', imagePath: 'assets/images/drizzile.png', region: 'Galar',
    entry: 'It extends its long, slimy tongue at blinding speeds and finishes off its prey with great skill.',
    ability: 'Torrent/Sniper',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/sobble.png',
    'assets/images/drizzile.png',
    'assets/images/inteleon.png',
    ]),
    Pokemon(name: 'Inteleon', type: 'Water', imagePath: 'assets/images/inteleon.png', region: 'Galar',
    entry: 'It uses special lenses in its eyes to sense things about its opponents—like their body heat—then attacks once it identifies a weak spot.',
    ability: 'Torrent/Sniper',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/sobble.png',
    'assets/images/drizzile.png',
    'assets/images/inteleon.png',
    ]),
    Pokemon(name: 'Sprigatito', type: 'Grass', imagePath: 'assets/images/sprigatito.png', region: 'Paldea',
    entry: 'Its fluffy fur is similar in composition to plants. This Pokémon frequently washes its face to keep it from drying out.',
    ability: 'Overgrow/Protean',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/sprigatito.png',
    'assets/images/floragato.png',
    'assets/images/meowscarada.png',
    ]),
    Pokemon(name: 'Floragato', type: 'Grass', imagePath: 'assets/images/floragato.png', region: 'Paldea',
    entry: 'Floragato deftly wields the vine hidden beneath its long fur, slamming the hard flower bud against its opponents.',
    ability: 'Overgrow/Protean',
    weakness: 'Fire/Ice/Poison/Flying/Bug',
    evolutions: [
    'assets/images/sprigatito.png',
    'assets/images/floragato.png',
    'assets/images/meowscarada.png',
    ]),
    Pokemon(name: 'Meowscarada', type: 'Grass/Dark', imagePath: 'assets/images/meowscarada.png', region: 'Paldea',
    entry: 'With skillful misdirection, it rigs foes with pollen- packed flower bombs. Meowscarada sets off the bombs before its foes realize whats going on.',
    ability: 'Overgrow/Protean',
    weakness: 'Fire/Ice/Fighting/Poison/Flying/Bug/Fairy',
    evolutions: [
    'assets/images/sprigatito.png',
    'assets/images/floragato.png',
    'assets/images/meowscarada.png',
    ]),
    Pokemon(name: 'Fuecoco', type: 'Fire', imagePath: 'assets/images/fuecoco.png', region: 'Paldea',
    entry: 'It lies on warm rocks and uses the heat absorbed by its square-shaped scales to create fire energy.',
    ability: 'Blaze/Unaware',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/fuecoco.png',
    'assets/images/crocalor.png',
    'assets/images/skeledirge.png',
    ]),
    Pokemon(name: 'Crocalor', type: 'Fire', imagePath: 'assets/images/crocalor.png', region: 'Paldea',
    entry: 'The combination of Crocalors fire energy and overflowing vitality has caused an egg-shaped fireball to appear on the Pokémons head.',
    ability: 'Blaze/Unaware',
    weakness: 'Water/Ground/Rock',
    evolutions: [
    'assets/images/fuecoco.png',
    'assets/images/crocalor.png',
    'assets/images/skeledirge.png',
    ]),
    Pokemon(name: 'Skeledirge', type: 'Fire/Ghost', imagePath: 'assets/images/skeledirge.png', region: 'Paldea',
    entry: 'Skeledirges gentle singing soothes the souls of all that hear it. It burns its enemies to a crisp with flames of over 5,400 degrees Fahrenheit.',
    ability: 'Blaze/Unaware',
    weakness: 'Water/Ground/Grock/Ghost/Dark',
    evolutions: [
    'assets/images/fuecoco.png',
    'assets/images/crocalor.png',
    'assets/images/skeledirge.png',
    ]),
    Pokemon(name: 'Quaxly', type: 'Water', imagePath: 'assets/images/quaxly.png', region: 'Paldea',
    entry: 'Its strong legs let it easily swim around in even fast-flowing rivers. It likes to keep things tidy and is prone to overthinking things.',
    ability: 'Torrent/Moxie',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/quaxly.png',
    'assets/images/quaxwell.png',
    'assets/images/quaquaval.png',
    ]),
    Pokemon(name: 'Quaxwell', type: 'Water', imagePath: 'assets/images/quaxwell.png', region: 'Paldea',
    entry: 'These Pokémon constantly run through shallow waters to train their legs, then compete with each other to see which of them kicks most gracefully.',
    ability: 'Torrent/Moxie',
    weakness: 'Grass/Electric',
    evolutions: [
    'assets/images/quaxly.png',
    'assets/images/quaxwell.png',
    'assets/images/quaquaval.png',
    ]),
    Pokemon(name: 'Quaquaval', type: 'Water/Fighting', imagePath: 'assets/images/quaquaval.png', region: 'Paldea',
    entry: 'A single kick from a Quaquaval can send a truck rolling. This Pokémon uses its powerful legs to perform striking dances from far-off lands.',
    ability: 'Torrent/Moxie',
    weakness: 'Grass/Electric/Flying/Fairy/Psychic',
    evolutions: [
    'assets/images/quaxly.png',
    'assets/images/quaxwell.png',
    'assets/images/quaquaval.png',
    ]),

  ];

  List<String> _regions = [
    'All',
    'Kanto',
    'Johto',
    'Hoenn',
    'Sinnoh',
    'Unova',
    'Kalos',
    'Alola',
    'Galar',
    'Paldea',
  ];

    @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text('Pokédex'),
      ),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            _buildFilterRow(),
            Expanded(
              child: _buildPokemonGrid(),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildFilterRow() {
    return Row(
      mainAxisAlignment: MainAxisAlignment.spaceBetween,
      children: [
        Text(
          'Filter by Region:',
          style: TextStyle(fontSize: 14.0, color: Colors.grey),
        ),
        DropdownButton<String>(
          value: _selectedRegion,
          items: _regions.map((region) {
            return DropdownMenuItem<String>(
              value: region,
              child: Text(region),
            );
          }).toList(),
          onChanged: (value) {
            setState(() {
              _selectedRegion = value!;
            });
          },
        ),
      ],
    );
  }

  Widget _buildPokemonGrid() {
    List<Pokemon> filteredList = _selectedRegion == 'All'
        ? _pokemonList
        : _pokemonList.where((pokemon) => pokemon.region == _selectedRegion).toList();

    return GridView.builder(
      gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
        crossAxisCount: 3,
        crossAxisSpacing: 8.0,
        mainAxisSpacing: 8.0,
      ),
      itemCount: filteredList.length,
      itemBuilder: (context, index) {
        return _buildPokemonCard(filteredList[index]);
      },
    );
  }

  Widget _buildPokemonCard(Pokemon pokemon) {
    return GestureDetector(
      onTap: () {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) => PokemonDetailPage(pokemon: pokemon),
          ),
        );
      },
      child: Card(
        elevation: 4.0,
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            Expanded(
              child: Image.asset(
                pokemon.imagePath,
                fit: BoxFit.cover,
              ),
            ),
            Padding(
              padding: const EdgeInsets.all(8.0),
              child: Text(
                pokemon.name,
                style: TextStyle(fontWeight: FontWeight.bold),
              ),
            ),
          ],
        ),
      ),
    );
  }
}